### ISSUE TITLE
Dead addon?

### ISSUE THREAD

**Issue by pitsi** [Twilight0/plugin.video.zouzounia.tv#1]
I had some time to spare this afternoon, so I gave zouzounia a chance. However, it does not seem to work at all,
This is the error I get when selecting "προσφατα βιντεο"
```
2021-07-12 18:46:11.561 T:139848338249472   ERROR: GetDirectory - Error getting plugin://plugin.video.zouzounia.tv/?action=videos&title=%ce%a0%cf%81%cf%8c%cf%83%cf%86%ce%b1%cf%84%ce%b1%20%ce%92%ce%af%ce%bd%cf%84%ce%b5%ce%bf
2021-07-12 18:46:11.582 T:139848513943680   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zouzounia.tv/?action=videos&title=%ce%a0%cf%81%cf%8c%cf%83%cf%86%ce%b1%cf%84%ce%b1%20%ce%92%ce%af%ce%bd%cf%84%ce%b5%ce%bf) failed
```
This one is from "λιστες αναπαραγωγης"
```
2021-07-12 18:48:06.386 T:139847238915840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.zouzounia.tv/addon.py", line 39, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.zouzounia.tv/addon.py", line 34, in main
                                                urldispatcher.dispatch(action, params)
                                              File "/storage/.kodi/addons/script.module.tulip/lib/tulip/url_dispatcher.py", line 95, in dispatch
                                                self.func_registry[action](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.zouzounia.tv/resources/lib/navigator.py", line 113, in playlists
                                                for p in self_list:
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
2021-07-12 18:48:06.491 T:139848346642176   ERROR: GetDirectory - Error getting plugin://plugin.video.zouzounia.tv/?action=playlists&title=%ce%9b%ce%af%cf%83%cf%84%ce%b5%cf%82%20%ce%91%ce%bd%ce%b1%cf%80%ce%b1%cf%81%ce%b1%ce%b3%cf%89%ce%b3%ce%ae%cf%82
2021-07-12 18:48:06.492 T:139848513943680   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zouzounia.tv/?action=playlists&title=%ce%9b%ce%af%cf%83%cf%84%ce%b5%cf%82%20%ce%91%ce%bd%ce%b1%cf%80%ce%b1%cf%81%ce%b1%ce%b3%cf%89%ce%b3%ce%ae%cf%82) failed
```
If it is dead, please consider removing it from your repo. I think it is old enough now and no one should have any expectations from it.
Testing was done on libreelec 9.2.6 with kodi 18.9.

**Comment by pitsi** [comment]
Closing the issue as this addon is officially dead and no longer in the repo.

**Comment by Twilight0** [comment]
@pitsi Indeed i no longer support the addon. Sorry for any inconvenience. It's easy to navigate through the youtube addon even without api keys.
